@hostlocal = http://localhost:3000
@hostremote = https://foragefriendapi.azurewebsites.net
@host={{hostremote}}

GET {{host}}/user

###

GET {{host}}/foragegroup/643a701fb9907319f4eaaa80

###

GET {{host}}/foragebiota/643be4077c5beaf35d7809cc

###

GET {{host}}/foragebiota/643a7035b9907319f4eaaa84/643a70bcb9907319f4eaaa9a

###

POST {{host}}/foragebiota/643be4077c5beaf35d7809cc
Content-Type: application/json

{
    "name": "Daisy",
    "isEdible": true,
    "imageURI": "An Image",
    "comment": "Test Comment"
}

###

DELETE {{host}}/foragebiota/643a5921cf12f02102ad9099/643a5bef10eed86621ac3c8d

###

DELETE {{host}}/foragebiota/643a5921cf12f02102ad9099

###
PATCH {{host}}/foragebiota/643a5921cf12f02102ad9099/643a5e0810eed86621ac3cb9
Content-Type: application/json

{
    "isEdible": false,
    "imageURI": "Updated Image",
    "comment": "Updated Comment"

}