@hostlocal = http://localhost:3000
@hostremote = https://foragefriendapi.azurewebsites.net
@host={{hostremote}}

GET {{host}}/user

###

GET {{host}}/user/643a6e1fa207a27c91bf86cc

###

POST {{host}}/user
Content-Type: application/json

{
    "name": "TestUser",
    "email": "TestUser@test.com",
    "password": "TestPassword",
    "token": "12345"
}

###

PATCH {{host}}/user/643a6e1fa207a27c91bf86cc
Content-Type: application/json

{
    "active": false,
    "email": "TestUser2@test.com",
    "name": "balls"
}

###

DELETE {{host}}/user/643a6e1fa207a27c91bf86cc

###