@hostlocal = http://localhost:3000
@hostremote = https://foragefriendapi.azurewebsites.net
@host={{hostlocal}}

@hostauthlocal =  http://localhost:8080/auth
@hostauthremote = https://foragefriendauth.azurewebsites.net/auth
@hostauth = {{hostauthlocal}}

# @name login
POST {{hostauth}}/realms/foragefriend/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password
&client_id=foragefriendapi
&client_secret=CQYXftPKTB9Rx9SuEqQ7ibLU6LWWkVJ4
&username=andy
&password=1234

###

@authToken = {{login.response.body.access_token}}

###

GET {{host}}/user/
Authorization: bearer {{authToken}}
Content-Type: application/json

###

GET {{host}}/user/64453c7bc177e780733557bd
Authorization: bearer {{authToken}}
Content-Type: application/json

###

POST {{host}}/user
Authorization: bearer {{authToken}}
Content-Type: application/json

{
    "username": "andy"
}

###

PATCH {{host}}/user/64453bd8a63cf12fe3a88a58
Authorization: bearer {{authToken}}
Content-Type: application/json

{
    "active": true
}

###

DELETE {{host}}/user/64453bd8a63cf12fe3a88a58
Authorization: bearer {{authToken}}
Content-Type: application/json

###
